version: '3.8'

services:
  logitrack-mysql:
    image: mysql:8.4
    container_name: logitrack-db-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_logitrack_password
      MYSQL_USER: logitrack_user
      MYSQL_PASSWORD: logitrack_password
      MYSQL_DATABASE: logitrack_db
    ports:
      - "3306:3306"
    volumes:
      - logitrack_mysql_data:/var/lib/mysql

  logitrack-phpmyadmin:
    image: phpmyadmin:latest
    container_name: logitrack-phpmyadmin-container
    restart: unless-stopped
    environment:
      PMA_HOST: logitrack-mysql
      PMA_PORT: 3306
    ports:
      - "5050:80"
    depends_on:
      - logitrack-mysql

volumes:
  logitrack_mysql_data:
